### ISSUE TITLE
汇编笔记Part 4. 80x86 指令系统处一个笔误

### ISSUE THREAD

**Issue by Slowist-Lee** [NoughtQ/notebook#20]
- 定位 link here: https://note.noughtq.top/lang/asm/4#_15
这里的`div op` 下面有一处笔误，该指令下面的`src`全部应该改成`op`
可参考：https://note.tonycrane.cc/cs/pl/asm/#_17

~~btw谢谢前辈的笔记捏，期末周又活了，之后发现问题再说x~~

**Comment by NoughtQ** [comment]
那我直接把`op`换成`src`，这样就只要改一处地方就行了hh，感谢指出，稍后我会修改上传的。

另外，我建议如果只发现少数笔误的话，就直接在下面的评论区指出就行；如果发现一堆错误的话就传在Issue里
